package e

const (
	// Success ...
	Success = 200
	// Error ...
	Error = 500

	// ErrorFindHomeDirectory ...
	ErrorFindHomeDirectory = 1001

	// ErrorDatabaseConnection ...
	ErrorDatabaseConnection = 10001

	// ErrorCreateService ...
	ErrorCreateService = 20001

	// ErrorCreateController ...
	ErrorCreateController = 30001

	// ErrorCreateRouter ...
	ErrorCreateRouter = 40001

	// ErrorLoadSettings ...
	ErrorLoadSettings = 50001
)
