version: '3'
services:
  cli:
    build:
      context: .
      dockerfile: ./docker/cli/Dockerfile
    container_name: cli
    env_file:
      - ./docker/cli/env
    restart: always
    # ports:
    #   - 8081:8081 # for debug
    volumes:
      - ./outputs:/outputs
      - ./settings.sample.yml:/app/settings.sample.yml
    networks:
      - default
      - shared-network
    command: >
      ./cli server -p 8081
  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    container_name: mysql
    env_file:
      - ./docker/mysql/env
    restart: always
    # ports: 
    #   - "3306:3306" # for debug
    volumes:
      - ./volumes/mysql/logs:/var/log/mysql
      - ./docker/mysql/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    networks:
      - default
      - shared-network

networks:
  shared-network:
    external: true
