version: '3'
services:
  cli:
    build:
      context: .
      dockerfile: ./docker/cli/Dockerfile
    container_name: cli
    env_file:
      - ./docker/cli/env
    restart: always
    volumes:
      - ./outputs:/outputs
    # docker-compose run --rm cli sh
    command: >
      ./cli --help
  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    container_name: mysql
    env_file:
      - ./docker/mysql/env
    restart: always
    ports: 
      - "3306:3306" # for debug
    volumes:
      - ./volumes/mysql/logs:/var/log/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
