database:
    dbms: mysql
    connect:
        user: root
        password: password
        protocol: tcp
        host: localhost
        port: 3306
        dbname: db
        dbargs: parseTime=true
