database:
    dbms: mysql
    connect:
        user: root
        password: password
        protocol: tcp
        host: localhost
        port: 3306
        db_name: db
        db_args: parseTime=true
