database:
    dbms: mysql
    connect:
        user: root
        password: password
        protocol: tcp
        host: mysql # for docker(specify `localhost` for local)
        port: 3306
        dbname: db
        dbargs: parseTime=true
